#:import utils kivy.utils

<mainClass>
    BoxLayout:

        orientation: 'vertical'

        size: root.width, root.height

        padding: (10, 10, 10, 10)

        spacing: 5

        Label:
            text:'Typing Go Burr'
            font_size: 20
            size_hint: None, None
            size: 100,50
            bold: True
            italic: True
            halign: 'center'
            valign: 'center'
            pos: 500,100

        TextInput:
            text:''
            size_hint: None,None
            size: 100,20
            foreground_color: (238/255, 238/255, 238/255)
            font_size: 40
            background_normal: ''
            background_color: (57/255, 62/255, 70/255)
            cursor_width: 10
            cursor_color: (121/255, 113/255, 234/255, 1)
            multiline: False
            allow_copy: False
            auto_indent: False
            use_handels: False
            text_align: 'center'

            


        